name: CI

on:
  push:
    branches: 
      - master
    tags:
      - "!*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install Gridsome CLI
      shell: bash
      run: |
        sudo npm install -g "@gridsome/cli"

    - name: Insall npm package
      shell: bash
      run: |
        npm install

    - name: Build
      shell: bash
      run: |
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: uploadkorea/uploadkorea.github.io.git
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./dist
